
project_id = "wwrthhjeqywhmthuogju"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
[functions.send-payment-reminder]
verify_jwt = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
webhook_port = 54323
server_port = 54324

[studio]
port = 54325
