// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwrthhjeqywhmthuogju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3cnRoaGplcXl3aG10aHVvZ2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMTI1NjIsImV4cCI6MjA1Nzc4ODU2Mn0.Hx_7mnLlyM6AyB9Monnh3TnUiRTlz5304pUgsbtM-FM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);